<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260112123140 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ACTIVIDADES_ODS (CODACTIVIDAD SMALLINT NOT NULL, ODS_ID INT NOT NULL, PRIMARY KEY (CODACTIVIDAD, ODS_ID))');
        $this->addSql('CREATE INDEX IDX_77A22A43C1F05EDB ON ACTIVIDADES_ODS (CODACTIVIDAD)');
        $this->addSql('CREATE INDEX IDX_77A22A43CED5F97 ON ACTIVIDADES_ODS (ODS_ID)');
        $this->addSql('CREATE TABLE ACTIVIDADES_HABILIDADES (CODACTIVIDAD SMALLINT NOT NULL, HABILIDAD_ID INT NOT NULL, PRIMARY KEY (CODACTIVIDAD, HABILIDAD_ID))');
        $this->addSql('CREATE INDEX IDX_D978BAD6C1F05EDB ON ACTIVIDADES_HABILIDADES (CODACTIVIDAD)');
        $this->addSql('CREATE INDEX IDX_D978BAD6CF65AA26 ON ACTIVIDADES_HABILIDADES (HABILIDAD_ID)');
        $this->addSql('CREATE TABLE ACTIVIDADES_NECESIDADES (CODACTIVIDAD SMALLINT NOT NULL, NECESIDAD_ID INT NOT NULL, PRIMARY KEY (CODACTIVIDAD, NECESIDAD_ID))');
        $this->addSql('CREATE INDEX IDX_E9643DC4C1F05EDB ON ACTIVIDADES_NECESIDADES (CODACTIVIDAD)');
        $this->addSql('CREATE INDEX IDX_E9643DC43CECC7E9 ON ACTIVIDADES_NECESIDADES (NECESIDAD_ID)');
        $this->addSql('CREATE TABLE HABILIDADES (id INT IDENTITY NOT NULL, nombre NVARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE INTERESES (id INT IDENTITY NOT NULL, nombre NVARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE NECESIDADES (id INT IDENTITY NOT NULL, nombre NVARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ODS (id INT IDENTITY NOT NULL, nombre NVARCHAR(100) NOT NULL, descripcion NVARCHAR(255), color NVARCHAR(7), PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE VOLUNTARIOS_HABILIDADES (DNI NCHAR(9) NOT NULL, HABILIDAD_ID INT NOT NULL, PRIMARY KEY (DNI, HABILIDAD_ID))');
        $this->addSql('CREATE INDEX IDX_C424E76BE92867B1 ON VOLUNTARIOS_HABILIDADES (DNI)');
        $this->addSql('CREATE INDEX IDX_C424E76BCF65AA26 ON VOLUNTARIOS_HABILIDADES (HABILIDAD_ID)');
        $this->addSql('CREATE TABLE VOLUNTARIOS_INTERESES (DNI NCHAR(9) NOT NULL, INTERES_ID INT NOT NULL, PRIMARY KEY (DNI, INTERES_ID))');
        $this->addSql('CREATE INDEX IDX_C12BB10AE92867B1 ON VOLUNTARIOS_INTERESES (DNI)');
        $this->addSql('CREATE INDEX IDX_C12BB10A6F2DFDAA ON VOLUNTARIOS_INTERESES (INTERES_ID)');
        $this->addSql('ALTER TABLE ACTIVIDADES_ODS ADD CONSTRAINT FK_77A22A43C1F05EDB FOREIGN KEY (CODACTIVIDAD) REFERENCES ACTIVIDADES (CODACTIVIDAD)');
        $this->addSql('ALTER TABLE ACTIVIDADES_ODS ADD CONSTRAINT FK_77A22A43CED5F97 FOREIGN KEY (ODS_ID) REFERENCES ODS (id)');
        $this->addSql('ALTER TABLE ACTIVIDADES_HABILIDADES ADD CONSTRAINT FK_D978BAD6C1F05EDB FOREIGN KEY (CODACTIVIDAD) REFERENCES ACTIVIDADES (CODACTIVIDAD)');
        $this->addSql('ALTER TABLE ACTIVIDADES_HABILIDADES ADD CONSTRAINT FK_D978BAD6CF65AA26 FOREIGN KEY (HABILIDAD_ID) REFERENCES HABILIDADES (id)');
        $this->addSql('ALTER TABLE ACTIVIDADES_NECESIDADES ADD CONSTRAINT FK_E9643DC4C1F05EDB FOREIGN KEY (CODACTIVIDAD) REFERENCES ACTIVIDADES (CODACTIVIDAD)');
        $this->addSql('ALTER TABLE ACTIVIDADES_NECESIDADES ADD CONSTRAINT FK_E9643DC43CECC7E9 FOREIGN KEY (NECESIDAD_ID) REFERENCES NECESIDADES (id)');
        $this->addSql('ALTER TABLE VOLUNTARIOS_HABILIDADES ADD CONSTRAINT FK_C424E76BE92867B1 FOREIGN KEY (DNI) REFERENCES VOLUNTARIOS (DNI)');
        $this->addSql('ALTER TABLE VOLUNTARIOS_HABILIDADES ADD CONSTRAINT FK_C424E76BCF65AA26 FOREIGN KEY (HABILIDAD_ID) REFERENCES HABILIDADES (id)');
        $this->addSql('ALTER TABLE VOLUNTARIOS_INTERESES ADD CONSTRAINT FK_C12BB10AE92867B1 FOREIGN KEY (DNI) REFERENCES VOLUNTARIOS (DNI)');
        $this->addSql('ALTER TABLE VOLUNTARIOS_INTERESES ADD CONSTRAINT FK_C12BB10A6F2DFDAA FOREIGN KEY (INTERES_ID) REFERENCES INTERESES (id)');
        $this->addSql('ALTER TABLE ACTIVIDADES DROP COLUMN ODS');
        $this->addSql('ALTER TABLE ACTIVIDADES DROP COLUMN HABILIDADES');
        $this->addSql('DROP INDEX UQ__ORGANIZA__161CF724A1301C9D ON ORGANIZACIONES');
        $this->addSql('ALTER TABLE ORGANIZACIONES ALTER COLUMN CP CHAR(5) NOT NULL');
        $this->addSql('ALTER TABLE VOLUNTARIOS DROP COLUMN HABILIDADES');
        $this->addSql('ALTER TABLE VOLUNTARIOS DROP COLUMN INTERESES');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA db_accessadmin');
        $this->addSql('CREATE SCHEMA db_backupoperator');
        $this->addSql('CREATE SCHEMA db_datareader');
        $this->addSql('CREATE SCHEMA db_datawriter');
        $this->addSql('CREATE SCHEMA db_ddladmin');
        $this->addSql('CREATE SCHEMA db_denydatareader');
        $this->addSql('CREATE SCHEMA db_denydatawriter');
        $this->addSql('CREATE SCHEMA db_owner');
        $this->addSql('CREATE SCHEMA db_securityadmin');
        $this->addSql('ALTER TABLE ACTIVIDADES_ODS DROP CONSTRAINT FK_77A22A43C1F05EDB');
        $this->addSql('ALTER TABLE ACTIVIDADES_ODS DROP CONSTRAINT FK_77A22A43CED5F97');
        $this->addSql('ALTER TABLE ACTIVIDADES_HABILIDADES DROP CONSTRAINT FK_D978BAD6C1F05EDB');
        $this->addSql('ALTER TABLE ACTIVIDADES_HABILIDADES DROP CONSTRAINT FK_D978BAD6CF65AA26');
        $this->addSql('ALTER TABLE ACTIVIDADES_NECESIDADES DROP CONSTRAINT FK_E9643DC4C1F05EDB');
        $this->addSql('ALTER TABLE ACTIVIDADES_NECESIDADES DROP CONSTRAINT FK_E9643DC43CECC7E9');
        $this->addSql('ALTER TABLE VOLUNTARIOS_HABILIDADES DROP CONSTRAINT FK_C424E76BE92867B1');
        $this->addSql('ALTER TABLE VOLUNTARIOS_HABILIDADES DROP CONSTRAINT FK_C424E76BCF65AA26');
        $this->addSql('ALTER TABLE VOLUNTARIOS_INTERESES DROP CONSTRAINT FK_C12BB10AE92867B1');
        $this->addSql('ALTER TABLE VOLUNTARIOS_INTERESES DROP CONSTRAINT FK_C12BB10A6F2DFDAA');
        $this->addSql('DROP TABLE ACTIVIDADES_ODS');
        $this->addSql('DROP TABLE ACTIVIDADES_HABILIDADES');
        $this->addSql('DROP TABLE ACTIVIDADES_NECESIDADES');
        $this->addSql('DROP TABLE HABILIDADES');
        $this->addSql('DROP TABLE INTERESES');
        $this->addSql('DROP TABLE NECESIDADES');
        $this->addSql('DROP TABLE ODS');
        $this->addSql('DROP TABLE VOLUNTARIOS_HABILIDADES');
        $this->addSql('DROP TABLE VOLUNTARIOS_INTERESES');
        $this->addSql('ALTER TABLE ACTIVIDADES ADD ODS VARCHAR(MAX)');
        $this->addSql('ALTER TABLE ACTIVIDADES ADD HABILIDADES VARCHAR(MAX)');
        $this->addSql('ALTER TABLE ORGANIZACIONES ALTER COLUMN CP NCHAR(5) NOT NULL');
        $this->addSql('CREATE UNIQUE NONCLUSTERED INDEX UQ__ORGANIZA__161CF724A1301C9D ON ORGANIZACIONES (EMAIL) WHERE EMAIL IS NOT NULL');
        $this->addSql('ALTER TABLE VOLUNTARIOS ADD HABILIDADES VARCHAR(MAX)');
        $this->addSql('ALTER TABLE VOLUNTARIOS ADD INTERESES VARCHAR(MAX)');
    }
}
