<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260115091520 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ACTIVIDADES (CODACTIVIDAD SMALLINT IDENTITY NOT NULL, NOMBRE NVARCHAR(40) NOT NULL, ESTADO NVARCHAR(255) NOT NULL, ESTADO_APROBACION NVARCHAR(20) NOT NULL, ESTADO_NEW NVARCHAR(255), DIRECCION NVARCHAR(40) NOT NULL, FECHA_INICIO DATETIME2(6) NOT NULL, FECHA_FIN DATETIME2(6) NOT NULL, MAX_PARTICIPANTES SMALLINT NOT NULL, CIF_EMPRESA NCHAR(9), PRIMARY KEY (CODACTIVIDAD))');
        $this->addSql('CREATE INDEX IDX_FED6DA367DF202BB ON ACTIVIDADES (CIF_EMPRESA)');
        $this->addSql('ALTER TABLE ACTIVIDADES ADD DEFAULT \'PENDIENTE\' FOR ESTADO_APROBACION');
        $this->addSql('CREATE TABLE ACTIVIDADES_ODS (CODACTIVIDAD SMALLINT NOT NULL, ODS_ID INT NOT NULL, PRIMARY KEY (CODACTIVIDAD, ODS_ID))');
        $this->addSql('CREATE INDEX IDX_77A22A43C1F05EDB ON ACTIVIDADES_ODS (CODACTIVIDAD)');
        $this->addSql('CREATE INDEX IDX_77A22A43CED5F97 ON ACTIVIDADES_ODS (ODS_ID)');
        $this->addSql('CREATE TABLE ACTIVIDADES_HABILIDADES (CODACTIVIDAD SMALLINT NOT NULL, HABILIDAD_ID INT NOT NULL, PRIMARY KEY (CODACTIVIDAD, HABILIDAD_ID))');
        $this->addSql('CREATE INDEX IDX_D978BAD6C1F05EDB ON ACTIVIDADES_HABILIDADES (CODACTIVIDAD)');
        $this->addSql('CREATE INDEX IDX_D978BAD6CF65AA26 ON ACTIVIDADES_HABILIDADES (HABILIDAD_ID)');
        $this->addSql('CREATE TABLE ACTIVIDADES_NECESIDADES (CODACTIVIDAD SMALLINT NOT NULL, NECESIDAD_ID INT NOT NULL, PRIMARY KEY (CODACTIVIDAD, NECESIDAD_ID))');
        $this->addSql('CREATE INDEX IDX_E9643DC4C1F05EDB ON ACTIVIDADES_NECESIDADES (CODACTIVIDAD)');
        $this->addSql('CREATE INDEX IDX_E9643DC43CECC7E9 ON ACTIVIDADES_NECESIDADES (NECESIDAD_ID)');
        $this->addSql('CREATE TABLE CICLOS (CURSO SMALLINT NOT NULL, NOMBRE NVARCHAR(100) NOT NULL, PRIMARY KEY (CURSO, NOMBRE))');
        $this->addSql('CREATE TABLE HABILIDADES (id INT IDENTITY NOT NULL, nombre NVARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE INSCRIPCIONES (id INT IDENTITY NOT NULL, ESTADO NVARCHAR(20) NOT NULL, DNI_VOLUNTARIO NCHAR(9), CODACTIVIDAD SMALLINT, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B7CF67D413E7C02 ON INSCRIPCIONES (DNI_VOLUNTARIO)');
        $this->addSql('CREATE INDEX IDX_2B7CF67DC1F05EDB ON INSCRIPCIONES (CODACTIVIDAD)');
        $this->addSql('CREATE TABLE INTERESES (id INT IDENTITY NOT NULL, nombre NVARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE NECESIDADES (id INT IDENTITY NOT NULL, nombre NVARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ODS (id INT IDENTITY NOT NULL, nombre NVARCHAR(100) NOT NULL, descripcion NVARCHAR(255), color NVARCHAR(7), PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ORGANIZACIONES (CIF NCHAR(9) NOT NULL, NOMBRE NVARCHAR(40) NOT NULL, EMAIL VARCHAR(100) NOT NULL UNIQUE, SECTOR NVARCHAR(100), DIRECCION NVARCHAR(40) NOT NULL, LOCALIDAD NVARCHAR(40) NOT NULL, CP CHAR(5) NOT NULL, DESCRIPCION NVARCHAR(200) NOT NULL, CONTACTO NVARCHAR(40) NOT NULL, ESTADO NVARCHAR(20) NOT NULL, PRIMARY KEY (CIF))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3295227310C6BEC4 ON ORGANIZACIONES (EMAIL) WHERE EMAIL IS NOT NULL');
        $this->addSql('CREATE TABLE VOLUNTARIOS (DNI NCHAR(9) NOT NULL, NOMBRE NVARCHAR(40) NOT NULL, APELLIDO1 NVARCHAR(40) NOT NULL, APELLIDO2 NVARCHAR(40) NOT NULL, CORREO NVARCHAR(40) NOT NULL, ZONA NVARCHAR(100), FECHA_NACIMIENTO DATETIME2(6) NOT NULL, EXPERIENCIA NVARCHAR(200), COCHE BIT NOT NULL, DISPONIBILIDAD VARCHAR(MAX), IDIOMAS VARCHAR(MAX), ESTADO_VOLUNTARIO NVARCHAR(20) NOT NULL, CURSO_CICLOS SMALLINT, NOMBRE_CICLOS NVARCHAR(100), PRIMARY KEY (DNI))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CC29E0C987FCCC4F ON VOLUNTARIOS (CORREO) WHERE CORREO IS NOT NULL');
        $this->addSql('CREATE INDEX IDX_CC29E0C94F5222D9CCB2DE43 ON VOLUNTARIOS (CURSO_CICLOS, NOMBRE_CICLOS)');
        $this->addSql('CREATE TABLE VOLUNTARIOS_HABILIDADES (DNI NCHAR(9) NOT NULL, HABILIDAD_ID INT NOT NULL, PRIMARY KEY (DNI, HABILIDAD_ID))');
        $this->addSql('CREATE INDEX IDX_C424E76BE92867B1 ON VOLUNTARIOS_HABILIDADES (DNI)');
        $this->addSql('CREATE INDEX IDX_C424E76BCF65AA26 ON VOLUNTARIOS_HABILIDADES (HABILIDAD_ID)');
        $this->addSql('CREATE TABLE VOLUNTARIOS_INTERESES (DNI NCHAR(9) NOT NULL, INTERES_ID INT NOT NULL, PRIMARY KEY (DNI, INTERES_ID))');
        $this->addSql('CREATE INDEX IDX_C12BB10AE92867B1 ON VOLUNTARIOS_INTERESES (DNI)');
        $this->addSql('CREATE INDEX IDX_C12BB10A6F2DFDAA ON VOLUNTARIOS_INTERESES (INTERES_ID)');
        $this->addSql('ALTER TABLE ACTIVIDADES ADD CONSTRAINT FK_FED6DA367DF202BB FOREIGN KEY (CIF_EMPRESA) REFERENCES ORGANIZACIONES (CIF)');
        $this->addSql('ALTER TABLE ACTIVIDADES_ODS ADD CONSTRAINT FK_77A22A43C1F05EDB FOREIGN KEY (CODACTIVIDAD) REFERENCES ACTIVIDADES (CODACTIVIDAD)');
        $this->addSql('ALTER TABLE ACTIVIDADES_ODS ADD CONSTRAINT FK_77A22A43CED5F97 FOREIGN KEY (ODS_ID) REFERENCES ODS (id)');
        $this->addSql('ALTER TABLE ACTIVIDADES_HABILIDADES ADD CONSTRAINT FK_D978BAD6C1F05EDB FOREIGN KEY (CODACTIVIDAD) REFERENCES ACTIVIDADES (CODACTIVIDAD)');
        $this->addSql('ALTER TABLE ACTIVIDADES_HABILIDADES ADD CONSTRAINT FK_D978BAD6CF65AA26 FOREIGN KEY (HABILIDAD_ID) REFERENCES HABILIDADES (id)');
        $this->addSql('ALTER TABLE ACTIVIDADES_NECESIDADES ADD CONSTRAINT FK_E9643DC4C1F05EDB FOREIGN KEY (CODACTIVIDAD) REFERENCES ACTIVIDADES (CODACTIVIDAD)');
        $this->addSql('ALTER TABLE ACTIVIDADES_NECESIDADES ADD CONSTRAINT FK_E9643DC43CECC7E9 FOREIGN KEY (NECESIDAD_ID) REFERENCES NECESIDADES (id)');
        $this->addSql('ALTER TABLE INSCRIPCIONES ADD CONSTRAINT FK_2B7CF67D413E7C02 FOREIGN KEY (DNI_VOLUNTARIO) REFERENCES VOLUNTARIOS (DNI)');
        $this->addSql('ALTER TABLE INSCRIPCIONES ADD CONSTRAINT FK_2B7CF67DC1F05EDB FOREIGN KEY (CODACTIVIDAD) REFERENCES ACTIVIDADES (CODACTIVIDAD)');
        $this->addSql('ALTER TABLE VOLUNTARIOS ADD CONSTRAINT FK_CC29E0C94F5222D9CCB2DE43 FOREIGN KEY (CURSO_CICLOS, NOMBRE_CICLOS) REFERENCES CICLOS (CURSO, NOMBRE)');
        $this->addSql('ALTER TABLE VOLUNTARIOS_HABILIDADES ADD CONSTRAINT FK_C424E76BE92867B1 FOREIGN KEY (DNI) REFERENCES VOLUNTARIOS (DNI)');
        $this->addSql('ALTER TABLE VOLUNTARIOS_HABILIDADES ADD CONSTRAINT FK_C424E76BCF65AA26 FOREIGN KEY (HABILIDAD_ID) REFERENCES HABILIDADES (id)');
        $this->addSql('ALTER TABLE VOLUNTARIOS_INTERESES ADD CONSTRAINT FK_C12BB10AE92867B1 FOREIGN KEY (DNI) REFERENCES VOLUNTARIOS (DNI)');
        $this->addSql('ALTER TABLE VOLUNTARIOS_INTERESES ADD CONSTRAINT FK_C12BB10A6F2DFDAA FOREIGN KEY (INTERES_ID) REFERENCES INTERESES (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA db_accessadmin');
        $this->addSql('CREATE SCHEMA db_backupoperator');
        $this->addSql('CREATE SCHEMA db_datareader');
        $this->addSql('CREATE SCHEMA db_datawriter');
        $this->addSql('CREATE SCHEMA db_ddladmin');
        $this->addSql('CREATE SCHEMA db_denydatareader');
        $this->addSql('CREATE SCHEMA db_denydatawriter');
        $this->addSql('CREATE SCHEMA db_owner');
        $this->addSql('CREATE SCHEMA db_securityadmin');
        $this->addSql('ALTER TABLE ACTIVIDADES DROP CONSTRAINT FK_FED6DA367DF202BB');
        $this->addSql('ALTER TABLE ACTIVIDADES_ODS DROP CONSTRAINT FK_77A22A43C1F05EDB');
        $this->addSql('ALTER TABLE ACTIVIDADES_ODS DROP CONSTRAINT FK_77A22A43CED5F97');
        $this->addSql('ALTER TABLE ACTIVIDADES_HABILIDADES DROP CONSTRAINT FK_D978BAD6C1F05EDB');
        $this->addSql('ALTER TABLE ACTIVIDADES_HABILIDADES DROP CONSTRAINT FK_D978BAD6CF65AA26');
        $this->addSql('ALTER TABLE ACTIVIDADES_NECESIDADES DROP CONSTRAINT FK_E9643DC4C1F05EDB');
        $this->addSql('ALTER TABLE ACTIVIDADES_NECESIDADES DROP CONSTRAINT FK_E9643DC43CECC7E9');
        $this->addSql('ALTER TABLE INSCRIPCIONES DROP CONSTRAINT FK_2B7CF67D413E7C02');
        $this->addSql('ALTER TABLE INSCRIPCIONES DROP CONSTRAINT FK_2B7CF67DC1F05EDB');
        $this->addSql('ALTER TABLE VOLUNTARIOS DROP CONSTRAINT FK_CC29E0C94F5222D9CCB2DE43');
        $this->addSql('ALTER TABLE VOLUNTARIOS_HABILIDADES DROP CONSTRAINT FK_C424E76BE92867B1');
        $this->addSql('ALTER TABLE VOLUNTARIOS_HABILIDADES DROP CONSTRAINT FK_C424E76BCF65AA26');
        $this->addSql('ALTER TABLE VOLUNTARIOS_INTERESES DROP CONSTRAINT FK_C12BB10AE92867B1');
        $this->addSql('ALTER TABLE VOLUNTARIOS_INTERESES DROP CONSTRAINT FK_C12BB10A6F2DFDAA');
        $this->addSql('DROP TABLE ACTIVIDADES');
        $this->addSql('DROP TABLE ACTIVIDADES_ODS');
        $this->addSql('DROP TABLE ACTIVIDADES_HABILIDADES');
        $this->addSql('DROP TABLE ACTIVIDADES_NECESIDADES');
        $this->addSql('DROP TABLE CICLOS');
        $this->addSql('DROP TABLE HABILIDADES');
        $this->addSql('DROP TABLE INSCRIPCIONES');
        $this->addSql('DROP TABLE INTERESES');
        $this->addSql('DROP TABLE NECESIDADES');
        $this->addSql('DROP TABLE ODS');
        $this->addSql('DROP TABLE ORGANIZACIONES');
        $this->addSql('DROP TABLE VOLUNTARIOS');
        $this->addSql('DROP TABLE VOLUNTARIOS_HABILIDADES');
        $this->addSql('DROP TABLE VOLUNTARIOS_INTERESES');
    }
}
